spring:
  application:
    name: kafka-streams-methods
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.ameda.kev.kafkastreamsmethods.serdes.TransactionSerializer
    streams:
      application-id: fraud-detection-streams
      properties:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: com.ameda.kev.kafkastreamsmethods.serdes.TransactionSerde

# groupBy. Working with stateful functions when it comes to kafka streams
        state.dir: /home/ameda/Downloads/kafka-streams-logs

